        const config = {
            pageId: <?= json_encode($pageId) ?>,
            initialTitle: <?= json_encode($pageTitle) ?>,
            initialSlug: <?= json_encode($pageSlug) ?>,
            initialStatus: <?= json_encode($pageStatus) ?>,
            projectType: <?= json_encode($page['project_type'] ?? '') ?>,
            hasPhotoboothProjectSurface: <?= json_encode(! empty($hasPhotoboothProjectSurface)) ?>,
            initialOgImage: <?= json_encode($pageOgImage ?? '') ?>,
            initialEditorJson: <?= json_encode($initialEditorJson) ?>,
            saveUrl: <?= json_encode(site_url('editor/save/' . $pageId)) ?>,
            publishUrl: <?= json_encode(site_url('editor/publish/' . $pageId)) ?>,
            isLoggedIn: <?= json_encode($isLoggedIn) ?>,
            hasActiveMembership: <?= json_encode($hasActiveMembership) ?>,
            canUsePremiumFeatures: <?= json_encode($hasEditorPremiumAccess) ?>,
            canUseAiPremiumFeatures: <?= json_encode(! empty($hasAiPremiumAccess)) ?>,
            canUseGuestMemories: <?= json_encode(! empty($canUseGuestMemories)) ?>,
            canPublishCurrentPage: <?= json_encode(! empty($canPublishCurrentPage)) ?>,
            pageAccessTier: <?= json_encode($pageAccessTier ?? 'premium') ?>,
            plansUrl: <?= json_encode($plansUrl) ?>,
            loginUrl: <?= json_encode($loginUrl ?? site_url('login')) ?>,
            checkSlugUrl: <?= json_encode(site_url('editor/check-slug')) ?>,
            previewUrl: <?= json_encode(site_url('preview/' . $pageId)) ?>,
            mediaUrl: <?= json_encode(site_url('editor/media')) ?>,
            mediaUploadUrl: <?= json_encode(site_url('editor/media/upload')) ?>,
            mediaDeleteUrl: <?= json_encode(site_url('editor/media/delete')) ?>,
            audioLibraryUrl: <?= json_encode(site_url('editor/audio')) ?>,
            audioUploadUrl: <?= json_encode(site_url('editor/audio/upload')) ?>,
            audioChunkUploadUrl: <?= json_encode(site_url('editor/audio/upload-chunk')) ?>,
            audioUploadMaxFileSize: 4 * 1024 * 1024,
            audioUploadChunkSize: 1024 * 1024,
            mediaRemoveBgUrl: <?= json_encode(site_url('editor/media/remove-bg')) ?>,
            magicLayerEnabled: <?= json_encode(filter_var(env('MAGIC_LAYER_ENABLED', false), FILTER_VALIDATE_BOOLEAN)) ?>,
            mediaMagicLayerUrl: <?= json_encode(filter_var(env('MAGIC_LAYER_ENABLED', false), FILTER_VALIDATE_BOOLEAN) ? site_url('editor/media/magic-layer') : '') ?>,
            mediaMagicLayerTempUploadUrl: <?= json_encode(filter_var(env('MAGIC_LAYER_ENABLED', false), FILTER_VALIDATE_BOOLEAN) ? site_url('editor/media/magic-layer-temp-upload') : '') ?>,
            mediaMagicLayerTempDeleteUrl: <?= json_encode(filter_var(env('MAGIC_LAYER_ENABLED', false), FILTER_VALIDATE_BOOLEAN) ? site_url('editor/media/magic-layer-temp-delete') : '') ?>,
            magicLayerTextMasks: <?= json_encode(filter_var(env('MAGIC_LAYER_TEXT_MASKS', false), FILTER_VALIDATE_BOOLEAN)) ?>,
            saveTemplateUrl: <?= json_encode($saveTemplateUrl ?? site_url('admin/templates/from-editor')) ?>,
            updateTemplateUrl: <?= json_encode($updateTemplateUrl ?? '') ?>,
            canUpdateSavedTemplate: <?= json_encode(! empty($canUpdateSavedTemplate)) ?>,
            saveTemplateTargets: <?= json_encode($saveTemplateTargets ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>,
            templatePreviewBaseUrl: <?= json_encode(site_url('templates/preview')) ?>,
            editorAssetLibraryUrl: <?= json_encode(site_url('editor/assets/library')) ?>,
            editorAssetUsageUrl: <?= json_encode(site_url('editor/assets/usage')) ?>,
            editorAssetUploadUrl: <?= json_encode(site_url('editor-assets/upload')) ?>,
            editorAssetCategoryUrl: <?= json_encode(site_url('editor-assets/category')) ?>,
            editorAssetDeleteUrl: <?= json_encode(site_url('editor-assets/delete')) ?>,
            editorAssetUploadToken: <?= json_encode($editorAssetUploadToken ?? '') ?>,
            customFontCssUrl: <?= json_encode($customFontCssUrl ?? site_url('custom-fonts.css')) ?>,
            isAdmin: <?= json_encode(! empty($isAdmin)) ?>,
            canManageEditorAssets: <?= json_encode(! empty($canManageEditorAssets)) ?>,
            canSaveTemplate: <?= json_encode(! empty($canSaveTemplate)) ?>,
            publishedDomain: <?= json_encode($publishedDomain ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>,
            publishedDomainOptions: <?= json_encode($publishedDomainOptions ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>,
            importReferenceEnabled: <?= json_encode(! empty($canImportReference)) ?>,
            importReferenceUploadUrl: <?= json_encode(site_url('editor/' . $pageId . '/upload')) ?>,
            importReferenceMaxFileSize: 2 * 1024 * 1024,
            importReferenceMaxPixels: 24000000,
            importReferenceMaxDimension: 6000,
            referenceMapperEnabled: <?= json_encode(! empty($canUseReferenceMapper)) ?>,
            referenceMapperPlaceholderUrl: '',
            ocrTextEnabled: <?= json_encode(! empty($canUseOcrTextDetection)) ?>,
            ocrTextEngine: <?= json_encode((string) env('editor_ocr_text_engine', 'gemini-vision')) ?>,
            ocrTextUrl: <?= json_encode(site_url('editor/' . $pageId . '/ocr-text')) ?>,
            magicLayerOcrUrl: <?= json_encode(site_url('editor/' . $pageId . '/magic-layer-ocr')) ?>,
            acaraAiGenerateUrl: <?= json_encode(site_url('editor/' . $pageId . '/acara-ai-generate')) ?>,
            acaraAiMascotUrl: <?= json_encode(aa_asset_url('assets/img/2.png')) ?>,
            ocrTextTesseractScriptUrl: <?= json_encode(aa_asset_url('assets/vendor/tesseract/tesseract.min.js')) ?>,
            ocrTextTesseractWorkerUrl: <?= json_encode(aa_asset_url('assets/vendor/tesseract/worker.min.js')) ?>,
            ocrTextTesseractCoreUrl: <?= json_encode(aa_asset_url('assets/vendor/tesseract/core')) ?>,
            ocrTextTesseractLangUrl: <?= json_encode(aa_asset_url('assets/vendor/tesseract/lang')) ?>,
            ocrTextConfidenceAuto: 0.9,
            ocrTextConfidenceReview: 0.7,
            templateCategories: <?= json_encode($templateCategories ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>,
            photoboothDomainUrl: <?= json_encode(site_url('dashboard/pages/' . $pageId . '/photobooth-domain')) ?>,
            photoboothDomainProofUrl: <?= json_encode(site_url('dashboard/pages/' . $pageId . '/photobooth-domain/proof')) ?>,
            csrfName: <?= json_encode(function_exists('csrf_token') ? csrf_token() : '') ?>,
            csrfHash: <?= json_encode(function_exists('csrf_hash') ? csrf_hash() : '') ?>,
            publicBaseUrl: <?= json_encode(site_url('u/')) ?>,
        };

        const state = {
            initialized: false,
            canvas: null,
            zoom: 0.45,
            zoomManuallyAdjusted: false,
            pages: [],
            activePageIndex: 0,
            editMode: 'pages',
            projectIntent: '',
            photoboothFrames: [],
            activePhotoboothFrameIndex: 0,
            history: [],
            redo: [],
            isRestoring: false,
            isPreviewingAnimation: false,
            isCropping: false,
            cropTarget: null,
            cropBox: null,
            cropObjectStates: null,
            cropPanTarget: null,
            cropPanDrag: null,
            cropPanObjectStates: null,
            cropPanGhost: null,
            cropPanDirty: false,
            cropPanStartCrop: null,
            cropPanFinishButton: null,
            mediaMode: 'insert',
            mediaAssets: [],
            mediaLibraryLoaded: false,
            mediaDragAsset: null,
            musicBuiltinAudio: [],
            musicUploadedAudio: [],
            musicLibraryLoaded: false,
            musicLibraryLoading: false,
            musicUploading: false,
            editorAssets: [],
            editorAssetCategories: [],
            editorAssetType: 'all',
            editorAssetCategory: '',
            editorAssetQuery: '',
            editorAssetVisible: 40,
            editorAssetMenuId: null,
            editorAssetMeta: null,
            slugAvailable: false,
            publicUrl: config.publicBaseUrl + (config.initialSlug || ''),
            fontRefreshDone: false,
            bunnyFontLoadPromises: {},
            googleFontLoadPromises: {},
            customFontLoadPromises: {},
            initializing: false,
            guestbook: defaultGuestbookConfig(),
            opening: defaultOpeningConfig(),
            clipboardObjectJson: null,
            contextMenuTarget: null,
            contextMenuPointer: null,
            contextImageTarget: null,
            animationPopoverTrigger: null,
            hoverTarget: null,
            cropDomDrag: null,
            countdownPickerDate: null,
            countdownPickerAnchor: null,
            fontDrawerTarget: 'text',
            fontDrawerGroup: 'all',
            fontDrawerQuery: '',
            fontDrawerWeightFamily: '',
            fontDrawerSelectedWeight: null,
            colorDrawerTargetInput: null,
            colorDrawerTitle: 'Color',
            colorPickerDragTarget: '',
            colorPickerPointerId: null,
            outlineColorFieldPointerId: null,
            hasUnsavedChanges: false,
            imageOutlineApplyTimer: null,
            pendingImageOutlineOptions: null,
            pendingNavigationUrl: null,
            allowNavigation: false,
        };

        const serializedObjectProps = [
            'id', 'name', 'customType', 'link', 'copyText', 'copyFeedback', 'locked', 'selectable', 'evented',
            'lockMovementX', 'lockMovementY', 'lockScalingX', 'lockScalingY', 'lockRotation', 'hasControls', 'hasBorders',
            'customAnimation',
            'aaAnimation', 'animation', 'animationName', 'animationPreset',
            'animationDelay', 'aaAnimationDelay', 'animationDuration', 'aaAnimationDuration',
            'animationOrderMode', 'aaAnimationOrder', 'aaAnimationIntensity', 'aaAnimationLoop',
            'aaTextAnimation',
            'excludeFromAnimation',
            'assetId', 'assetType', 'assetCategory',
            'isGalleryPhoto', 'galleryZoom', 'galleryImageSrc', 'galleryImageName',
            'isGuestName', 'dynamicKey', 'templateText', 'showCloseButton', 'glassCard',
            'glassBackgroundColor', 'closeButtonColor',
            'cropX', 'cropY', 'clipPath', 'src', 'crossOrigin', 'aaOriginalImageSrc', 'aaOriginalImageName',
            'aaMediaKind', 'aaAnimatedSrc',
            'aaImportReference', 'aaImportReferenceMode',
            'aaReferenceMapped', 'aaReferenceRegionKind', 'aaReferenceRegionId',
            'aaSource', 'aaOcrConfidence', 'aaFontMatchConfidence', 'aaNeedsBackgroundCleanup',
            'aaOcrStatus', 'aaOcrBlockId', 'aaOcrFontAlternatives',
            'aaGeminiDecorationKind', 'aaGeminiDecorationAsset', 'aaMagicLayerAutoTrim',
            'aaMagicLayerSplitComponent', 'aaMagicLayerComponentIndex',
            'aaRemovedBg', 'aaRemovedBgSrc', 'aaImageOutlineBaseSrc', 'aaImageOutlineColor', 'aaImageOutlineWidth',
            'aaImageOutlineDraftColor', 'aaImageOutlineDraftWidth',
            'aaImageOutlineAppliedSrc', 'aaImageAlphaOutline', 'aaImageOutlineAlphaEligible',
            'aaBgOffsetX', 'aaBgOffsetY',
            'borderRadius', 'stroke', 'strokeWidth', 'strokeDashArray', 'strokeUniform', 'imageStrokeStyle',
            'aaMaterialType', 'aaMaterialPreset', 'aaMaterialFallback',
            'aaImageEffectPreset', 'aaImageOverlayGradient', 'aaImageFrameShape', 'aaImageRemoveColor',
            'aaFramePlaceholder', 'aaFramePlaceholderLabel',
            'aaPhotoboothSlot', 'aaPhotoboothSlotIndex', 'aaPhotoboothSlotCount', 'aaPhotoboothFrameKey',
            'aaProtectedObject', 'aaPreventDelete',
            'aaBusinessCategory', 'aaBusinessElement', 'aaBusinessSection',
            'paintFirst', 'shadow', 'charSpacing', 'lineHeight',
            'aaTextEffectPreset', 'aaTextEffectOutlineColor', 'aaTextEffectShadowColor',
            'fontWeight', 'fontStyle', 'underline', 'linethrough', 'placeholder', 'label', 'fieldName',
            'options',
            'buttonText', 'required', 'stickerSource', 'maxLength', 'formGroupId', 'guestbookRole',
            'audioUrl', 'autoplayAfterInteraction', 'loopAudio', 'showPlayerButton',
            'youtubeUrl', 'youtubeVideoId', 'youtubeAutoplayOnView', 'youtubeLoop',
            'controlBackground', 'controlTextColor', 'controlRadius', 'musicButtonShape',
            'openingButtonPadding', 'openingButtonPaddingY', 'openingButtonFontFamily',
            'countdownDate', 'countdownTime', 'countdownTarget', 'countdownGap', 'countdownCardHeight',
            'countdownFontFamily', 'countdownFontSize', 'countdownTextColor',
            'galleryImages', 'galleryItems', 'galleryColumns', 'galleryGap', 'galleryRadius',
            'galleryPreviewWidth', 'galleryPreviewHeight',
            'socialTitle', 'socialLinks', 'socialPlatform', 'socialLabel',
            'storyTitle', 'storyItems',
            'buttonAction', 'scrollTarget', 'lockPageScroll',
        ];

        const els = {};

        function $(id) {
            return document.getElementById(id);
        }

        function collectElements() {
            [
                'aaFabricCanvas', 'aaStage', 'aaStageViewport', 'aaStageWrap', 'aaZoomLabel', 'aaSaveState',
                'aaImageInput',
                'aaEditorToast', 'aaEditorToastIcon', 'aaEditorToastTitle', 'aaEditorToastMessage',
                'aaEditorToastClose',
                'editorAccessModal', 'editorAccessModalTitle', 'editorAccessModalDescription', 'editorAccessModalPrimary',
                'aaObjectContextMenu', 'aaObjectFloatingToolbar', 'aaInteractionPopover', 'aaLinkPopoverSection',
                'aaSocialPopoverSection', 'aaSocialPopoverPlatformInput', 'aaSocialPopoverLabelInput',
                'aaSocialPopoverUrlInput', 'aaCopyPopoverSection', 'aaLinkPopoverUrlInput', 'aaCopyPopoverTextInput',
                'aaCopyPopoverFeedbackInput', 'aaMusicPopoverSection', 'aaMusicPopoverUrlInput',
                'aaMusicPopoverBgInput', 'aaMusicPopoverRadiusInput', 'aaMusicPopoverRadiusValue',
                'aaMusicPopoverAutoplayInput', 'aaMusicPopoverLoopInput', 'aaMusicPopoverShowButtonInput',
                'aaYoutubePopoverSection', 'aaYoutubePopoverUrlInput', 'aaYoutubePopoverBgInput',
                'aaYoutubePopoverRadiusInput', 'aaYoutubePopoverRadiusValue',
                'aaYoutubePopoverAutoplayInput', 'aaYoutubePopoverLoopInput',
                'aaOpeningButtonPopoverSection', 'aaOpeningButtonBgInput', 'aaOpeningButtonTextColorInput',
                'aaOpeningButtonFontInput', 'aaOpeningButtonRadiusInput', 'aaOpeningButtonRadiusValue',
                'aaOpeningButtonPaddingYInput', 'aaOpeningButtonPaddingYValue',
                'aaGuestFieldPopoverSection', 'aaGuestFieldPopoverTextInput', 'aaGuestFieldPopoverBgInput',
                'aaGuestFieldPopoverFontInput', 'aaGuestFieldPopoverSizeInput', 'aaGuestFieldPopoverColorInput',
                'aaGuestFieldPopoverRadiusInput', 'aaGuestFieldPopoverRadiusValue',
                'aaGuestFieldPopoverRequiredWrap', 'aaGuestFieldPopoverRequiredInput',
                'aaGuestFieldPopoverMaxWrap', 'aaGuestFieldPopoverMaxInput',
                'aaMediaDropPreview',
                'aaMediaDropPreviewImage', 'aaMediaDropPreviewLabel', 'aaCropDomOverlay',
                'aaCropFloatingToolbar', 'aaCropFloatApplyBtn', 'aaCropFloatCancelBtn', 'aaCropFloatResetBtn',
                'aaFloatingLockBtn', 'aaFloatingDuplicateBtn', 'aaFloatingDeleteBtn', 'aaFloatingInteractionBtn',
                'aaFloatingMoreBtn',
                'aaContextToolbar', 'aaContextColorBtn', 'aaContextColorInput', 'aaContextColorSwatch',
                'aaContextStrokeBtn', 'aaContextStrokePopover', 'aaContextStrokeColorInput',
                'aaContextStrokeInput', 'aaContextStrokeValue',
                'aaContextRadiusBtn', 'aaContextRadiusPopover', 'aaContextRadiusInput',
                'aaContextRadiusValue', 'aaContextCropBtn', 'aaContextRemoveBgBtn', 'aaContextMagicLayerBtn', 'aaContextFlipBtn', 'aaContextFlipPopover',
                'aaContextImageOutlineBtn', 'aaContextImageOutlinePopover', 'aaContextImageOutlineColorInput',
                'aaOutlineColorField', 'aaOutlineColorHandle', 'aaOutlineHueInput', 'aaOutlineColorHexInput',
                'aaOutlineColorPreview', 'aaOutlineColorPreviewText', 'aaOutlineRecentColorWrap',
                'aaOutlineRecentColorList',
                'aaContextImageOutlineWidthInput', 'aaContextImageOutlineWidthValue',
                'aaContextImageOutlineResetBtn', 'aaContextImageOutlineApplyBtn',
                'aaContextImageEffectsBtn', 'aaContextImageEffectsPopover',
                'aaContextImageFrameBtn', 'aaContextImageFramePopover',
                'aaContextOpacityBtn',
                'aaContextTransparencyPopover', 'aaContextTransparencyInput', 'aaContextTransparencyValue',
                'aaContextAnimateBtn',
                'aaCountdownContextToolbar', 'aaCountdownContextDateInput', 'aaCountdownContextDatePickerBtn',
                'aaCountdownContextTimeInput', 'aaCountdownContextBgInput', 'aaCountdownContextRadiusInput',
                'aaCountdownContextGapInput',
                'aaCountdownContextFontInput', 'aaCountdownContextSizeInput', 'aaCountdownContextColorInput',
                'aaLeftDrawerCloseBtn',
                'aaMagicLayerAiBtn', 'aaMagicLayerAiStatus', 'aaMagicLayerFileInput',
                'aaMagicLayerPreview', 'aaMagicLayerPreviewImage', 'aaMagicLayerPreviewMeta',
                'aaMagicLayerProcessBtn', 'aaMagicLayerClearBtn',
                'aaMusicDrawerStatus', 'aaMusicDrawerTitle', 'aaMusicDrawerSubtitle',
                'aaMusicDrawerUrlInput', 'aaMusicDrawerBgInput', 'aaMusicDrawerRadiusInput',
                'aaMusicDrawerShapeInput', 'aaMusicDrawerAutoplayInput', 'aaMusicDrawerLoopInput',
                'aaMusicDrawerShowButtonInput', 'aaMusicDrawerUploadBtn', 'aaMusicDrawerFileInput',
                'aaMusicDrawerUploadStatus', 'aaMusicBuiltinList', 'aaMusicUploadedList', 'aaMusicDrawerList',
                'aaElementDrawerTitle', 'aaElementDrawerStatus', 'aaElementDrawerMount',
                'aaMobileInteractionDrawer',
                'aaMobileLinkSection', 'aaMobileLinkUrlInput',
                'aaMobileSocialSection', 'aaMobileSocialPlatformInput', 'aaMobileSocialLabelInput',
                'aaMobileSocialUrlInput',
                'aaMobileCopySection', 'aaMobileCopyTextInput', 'aaMobileCopyFeedbackInput',
                'aaMobileYoutubeSection', 'aaMobileYoutubeUrlInput', 'aaMobileYoutubeBgInput',
                'aaMobileYoutubeRadiusInput', 'aaMobileYoutubeRadiusValue',
                'aaMobileYoutubeAutoplayInput', 'aaMobileYoutubeLoopInput',
                'aaMobileOpeningButtonSection', 'aaMobileOpeningButtonBgInput',
                'aaMobileOpeningButtonTextColorInput', 'aaMobileOpeningButtonFontInput',
                'aaMobileOpeningButtonRadiusInput', 'aaMobileOpeningButtonRadiusValue',
                'aaMobileOpeningButtonPaddingYInput', 'aaMobileOpeningButtonPaddingYValue',
                'aaMobileGuestFieldSection', 'aaMobileGuestFieldTextInput', 'aaMobileGuestFieldBgInput',
                'aaMobileGuestFieldFontInput', 'aaMobileGuestFieldSizeInput', 'aaMobileGuestFieldColorInput',
                'aaMobileGuestFieldRadiusInput', 'aaMobileGuestFieldRadiusValue',
                'aaMobileGuestFieldRequiredWrap', 'aaMobileGuestFieldRequiredInput',
                'aaMobileGuestFieldMaxWrap', 'aaMobileGuestFieldMaxInput',
	                'aaMobileGallerySection', 'aaMobileGalleryUploadBtn', 'aaMobileGalleryPickMediaBtn',
	                'aaMobileGalleryItemListMount', 'aaMobileGalleryColumnsInput', 'aaMobileGalleryGapInput',
	                'aaMobileGalleryRadiusInput', 'aaMobileGalleryRadiusValue',
		                'aaMobileGalleryPhotoSection', 'aaMobileGalleryPhotoUploadBtn',
		                'aaMobileGalleryPhotoPickMediaBtn', 'aaMobileGalleryPhotoZoomInput',
                'aaMobileImageSection', 'aaMobileImageUploadBtn', 'aaMobileImagePickMediaBtn',
                'aaMobileImageRadiusInput', 'aaMobileImageRadiusValue',
                'aaMobileFrameSection', 'aaMobileFrameUploadBtn', 'aaMobileFramePickMediaBtn',
                'aaFramePlaceholderActions', 'aaFramePlaceholderUploadBtn', 'aaFramePlaceholderPickMediaBtn',
		                'aaSocialSettings', 'aaSocialTitleInput', 'aaSocialInstagramInput', 'aaSocialTiktokInput',
                'aaSocialThreadsInput', 'aaSocialXInput', 'aaSocialFacebookInput', 'aaSocialYoutubeInput',
                'aaStorySettings', 'aaStoryTitleInput', 'aaStoryItemsInput',
                'aaAcaraAiPromptInput', 'aaAcaraAiAttachBtn', 'aaAcaraAiSendBtn', 'aaAcaraAiNewChatBtn',
                'aaAcaraAiPageLabel',
                'aaAcaraAiChatLog', 'aaAcaraAiAttachmentClearBtn',
                'aaFontDrawerCloseBtn', 'aaFontDrawerSearch', 'aaFontDrawerChips', 'aaFontDrawerList',
                'aaColorDrawerCloseBtn', 'aaColorDrawerInput', 'aaColorDrawerHexInput',
                'aaColorEyedropperBtn', 'aaOutlineEyedropperBtn',
                'aaColorPickerField', 'aaColorPickerHandle', 'aaColorPickerHueBar', 'aaColorPickerHueHandle',
                'aaColorPickerPreview', 'aaColorPickerPreviewText',
                'aaColorDrawerAlphaWrap', 'aaColorDrawerAlphaInput', 'aaColorDrawerAlphaValue',
                'aaColorDrawerAlphaPreview', 'aaColorDrawerHint',
                'aaTextContextToolbar', 'aaMobileTextEditBtn', 'aaMobileTextDoneBtn', 'aaMobileTextCloseBtn',
                'aaTextContextFont', 'aaTextContextSizeDown', 'aaTextContextSizeValue',
                'aaTextContextSizeUp', 'aaTextContextColorBtn', 'aaTextContextColorInput',
                'aaTextContextColorSwatch',
                'aaTextContextBoldBtn', 'aaTextContextItalicBtn', 'aaTextContextUnderlineBtn',
                'aaTextContextStrikeBtn', 'aaTextContextCaseBtn', 'aaTextContextAlignBtn',
                'aaTextContextListBtn', 'aaTextContextOpacityBtn', 'aaTextContextEffectsBtn',
                'aaTextContextAnimateBtn', 'aaTextEffectsPopover',
                'aaAnimationPopover', 'aaTextEffectStrokeColor',
                'aaTextEffectStrokeWidth', 'aaTextEffectStrokeValue', 'aaTextEffectShadowColor',
                'aaTextEffectShadowBlur', 'aaTextEffectShadowBlurValue', 'aaTextEffectShadowOffsetX',
                'aaTextEffectShadowOffsetXValue', 'aaTextEffectShadowOffsetY',
                'aaTextEffectShadowOffsetYValue', 'aaTextEffectCharSpacing', 'aaTextEffectCharSpacingValue',
                'aaTextEffectLineHeight', 'aaTextEffectLineHeightValue', 'aaTextEffectGlowPreset',
                'aaTextEffectReset',
                'aaCanvasLoading',
                'aaBrandSaveState',
                'aaPageList', 'aaPageCount', 'aaEditPhotoboothBtn', 'aaEditOpeningBtn', 'aaEditPagesBtn',
                'aaPhotoboothEntryToast', 'aaPhotoboothEntryToastClose',
                'aaObjectControls', 'aaSelectionHint', 'aaTextInput', 'aaFontInput', 'aaFontSizeInput',
                'aaLayerList', 'aaLayerCount',
                'aaColorInput', 'aaBackgroundInput', 'aaBackgroundImageInput', 'aaUploadBackgroundBtn',
                'aaRemoveBackgroundBtn', 'aaBackgroundImageStatus', 'aaBackgroundOpacityInput',
                'aaBackgroundOpacityValue', 'aaBackgroundPositionXInput', 'aaBackgroundPositionXValue',
                'aaBackgroundPositionYInput', 'aaBackgroundPositionYValue',
                'aaBackgroundPositionResetBtn', 'aaMediaGrid', 'aaMediaUploadState',
                'aaMediaBulkBar', 'aaMediaSelectAllInput', 'aaDeleteSelectedMediaBtn',
                'aaPreviewModal',
                'aaPreviewFrame',
                'aaPublishModal', 'aaPublishChoiceView', 'aaPublishDetailView', 'aaPublishChoiceInvitationBtn',
                'aaPublishChoiceBusinessProfileBtn', 'aaPublishChoicePhotoboothBtn', 'aaClosePublishChoiceBtn', 'aaPublishBackBtn',
                'aaPublishPhotoboothBtn', 'aaOpenPhotoboothQrBtn', 'aaPhotoboothDomainModal',
                'aaPhotoboothDomainBackBtn',
                'aaPhotoboothDomainForm', 'aaPhotoboothDomainTitle', 'aaPhotoboothStandardUrl',
                'aaPhotoboothPreviewUrlInput', 'aaPhotoboothPreviewUrlCopyBtn',
                'aaPhotoboothReadyUrlInput', 'aaPhotoboothReadyUrlStatus', 'aaPhotoboothReadyUrlCopyBtn',
                'aaPhotoboothPublicUrlInput', 'aaPhotoboothPublicUrlCopyBtn',
                'aaPhotoboothPublicUrlStatus',
                'aaPhotoboothDomainStatus', 'aaPhotoboothDomainPrice', 'aaPhotoboothDomainNote',
                'aaPhotoboothDomainMessage', 'aaPhotoboothCustomDomainInput', 'aaPhotoboothDomainQrBtn',
                'aaPhotoboothDomainOptions', 'aaPhotoboothDomainStatusPanel', 'aaPhotoboothDomainValue',
                'aaPhotoboothDomainSubmitBtn', 'aaPhotoboothDomainPaymentPanel', 'aaPhotoboothPaymentInstruction',
                'aaPhotoboothPaymentOrderStatus', 'aaPhotoboothPaymentCheckoutBtn', 'aaPhotoboothPaymentProofInput',
                'aaPhotoboothPaymentNoteInput', 'aaPhotoboothPaymentUploadBtn', 'aaPhotoboothPaymentProofStatus',
                'aaPublishTitleInput', 'aaPublishSlugInput', 'aaSlugStatus',
                'aaPublishSubdomainInput', 'aaPublishDomainPreview', 'aaPublishDomainStatus',
                'aaPublishSubdomainUrlInput', 'aaPublishSubdomainCopyBtn',
                'aaPublishWaUrlText', 'aaPublicUrlCopyBtn', 'aaPublishSaveDraftBtn', 'aaClosePublishSecondaryBtn',
                'aaPublicUrlInput', 'aaOpenPublicBtn', 'aaPublishOgImageInput', 'aaPublishOgPreview',
                'aaPublishOgStatus', 'aaPublishOgClearBtn', 'aaCropPanel', 'aaCropFields', 'aaCropXInput',
                'aaCropYInput',
                'aaCropWidthInput', 'aaCropHeightInput', 'aaCropHint', 'aaStartCropBtn', 'aaApplyCropBoxBtn',
                'aaCancelCropBtn', 'aaTemplateModal', 'aaTemplateNameInput',
                'aaTemplateSlugInput', 'aaTemplateCategoryInput', 'aaTemplateDescriptionInput',
                'aaColorMaterialSection',
                'aaTemplatePremiumInput', 'aaTemplateModeCreate', 'aaTemplateModeUpdate',
                'aaTemplateUpdatePanel', 'aaTemplateTargetInput', 'aaTemplateNewFields',
                'aaTemplateThumbnailHint', 'aaTemplatePremiumPanel', 'aaLinkPanel', 'aaCopyPanel', 'aaLinkUrlInput', 'aaCopyTextInput',
                'aaCopyFeedbackInput',
                'aaBoldBtn', 'aaItalicBtn', 'aaUnderlineBtn', 'aaImageRadiusPanel',
                'aaImageRadiusInput', 'aaImageRadiusValue', 'aaGuestbookPanel', 'aaGuestbookTitleInput',
                'aaGuestbookSubtitleInput', 'aaGuestbookButtonInput', 'aaGuestbookBgInput',
                'aaGuestbookCardInput', 'aaGuestbookTextInput', 'aaGuestbookAccentInput',
                'aaGuestbookRadiusInput', 'aaGuestbookMaxHeightInput', 'aaGuestbookStickerInput',
                'aaGuestbookAttendanceInput', 'aaGuestbookHideBtn', 'aaGuestbookEditorPreview',
                'aaGuestFieldBgPanel', 'aaGuestFieldBgInput',
                'aaGuestNameFormatPanel', 'aaGuestNameFormatInput', 'aaGuestNameBgInput',
                'aaGuestNameCloseInput',
                'aaInteractivePanel', 'aaMusicSettings', 'aaAudioUrlInput', 'aaAudioAutoplayInput',
                'aaAudioLoopInput', 'aaAudioShowButtonInput', 'aaCountdownSettings', 'aaCountdownDateInput',
                'aaCountdownDatePickerBtn', 'aaCountdownDatePicker', 'aaCountdownDatePrevBtn',
                'aaCountdownDateNextBtn', 'aaCountdownDateMonthLabel', 'aaCountdownDatePickerHead',
                'aaCountdownDatePickerGrid', 'aaCountdownTimeInput', 'aaCountdownGapInput',
                'aaInteractiveBgInput', 'aaInteractiveRadiusWrap', 'aaInteractiveRadiusInput',
                'aaScrollLockWrap', 'aaScrollLockInput', 'aaGallerySettings', 'aaGalleryImagesInput',
                'aaGalleryUploadBtn', 'aaGalleryPickMediaBtn', 'aaGalleryItemList', 'aaGalleryColumnsInput',
                'aaGalleryGapInput', 'aaGalleryRadiusInput',
                'aaTemplateSearchInput', 'aaTemplateSearchBtn', 'aaTemplateCategoryChips', 'aaTemplateCategoryView',
                'aaTemplateListView', 'aaTemplateBackBtn', 'aaTemplateCurrentCategoryTitle',
                'aaTemplateGrid', 'aaTemplateEmptyState', 'aaTemplateLoadingState',
                'aaTemplateDetailPopover',
                'aaTemplatePreviewModal', 'aaTemplatePreviewFrame', 'aaTemplatePreviewTitle',
                'aaCloseTemplatePreviewBtn', 'aaExitGuardModal', 'aaExitGuardSaveBtn', 'aaExitGuardCancelBtn',
                'aaEditorAssetGlobalSearchInput', 'aaEditorAssetGlobalSearchBtn',
                'aaEditorAssetQuickChips',
                'aaEditorAssetLandingSections',
                'aaEditorAssetSearchInput', 'aaEditorAssetTypeChips',
                'aaEditorAssetCategoryView', 'aaEditorAssetCategoryGrid', 'aaEditorAssetListView',
                'aaEditorAssetBackBtn', 'aaEditorAssetCurrentCategoryTitle',
                'aaEditorAssetGrid', 'aaEditorAssetMoreBtn', 'aaEditorAssetUploadForm',
                'aaEditorAssetUploadType', 'aaEditorAssetUploadCategory', 'aaEditorAssetUploadFile',
                'aaEditorAssetUploadPremium',
                'aaEditorAssetUploadBtn', 'aaEditorAssetUploadState',
                'aaImportReferenceTab',
                'aaImportReferenceFileInput', 'aaImportReferencePreview', 'aaImportReferencePreviewImage',
                'aaImportReferencePreviewMeta', 'aaImportReferencePageNameInput',
                'aaImportReferenceSizeInput', 'aaImportReferenceModeInput', 'aaImportReferenceCreateBtn',
                'aaReferenceMapperStartBtn', 'aaReferenceMapperStatus', 'aaReferenceMapperChoicePanel',
                'aaReferenceMapperFrameBtn', 'aaReferenceMapperTextBtn', 'aaReferenceMapperCancelBtn',
                'aaReferenceMapperTextPanel', 'aaReferenceMapperTextInput', 'aaReferenceMapperNameInput',
                'aaReferenceMapperFontInput', 'aaReferenceMapperFontSizeInput', 'aaReferenceMapperColorInput',
                'aaReferenceMapperAlignInput', 'aaReferenceMapperWeightInput', 'aaReferenceMapperLineHeightInput',
                'aaReferenceMapperCoverInput', 'aaReferenceMapperCoverColorInput',
                'aaReferenceMapperCreateTextBtn', 'aaReferenceMapperBackBtn',
                'aaOcrTextDetectBtn', 'aaOcrTextStatus', 'aaOcrReviewPanel', 'aaOcrApplyBtn',
                'aaOcrCancelBtn', 'aaOcrCompareBtn', 'aaOcrReviewOnlyBtn', 'aaOcrChangeFontBtn',
            ].forEach(id => {
                els[id] = $(id);
            });
        }
